// Saloon / Bar generation and drawing — plan-driven (v31)
//
// Recreates the interior + exterior of a Western Saloon / Bar based on the
// Hyper3D Rodin reference model "Old Western saloon", using only the existing
// ctx.pb() renderer (no GLB / Three.js).
//
// v31 changes:
//   - False front is now a PARAPET above the flat roof (not a full-height
//     slab), so the front door + windows on the regular front wall are no
//     longer covered / clipped.
//   - Front windows sit on the regular front wall surface (z1+WALL_T/2),
//     not pushed into the false front.
//   - Added named interior props: Spittoon, WantedPoster01/02, SaloonPainting,
//     AntlerMount, CardDeck, PokerChips, PokerTableCloth, WhiskeyBottle,
//     BeerBarrel, BarTowel, WallSconce01/02.
//   - Added an upright Piano (from piano.js) against the west wall, with a
//     PianoStool.
//   - Code moved into src/game/bar/ folder.
//
// All coords are derived from the TOWN.saloon bounding box. A clear visitor
// path runs along x = b.x = -28.5 from the front door (z = z1) straight north
// to the bar counter (z ≈ -9.7). Tables sit either side of this path; stools
// sit in front of the counter; shelves sit on the back wall behind the bar.

import {
  TOWN, DOOR_GAP, DOOR_H, WALL_T, DOOR_SPEED, C,
  SALOON_INCLUDE_PIANO
} from '../config.js';
import { SALOON_LAYOUT } from './config.js';  // ✅ scaled layout from bar/config.js
import { V3 } from '../math.js';
import { drawPiano, drawPianoStool } from './piano.js';
import { drawBatwingDoors } from './batwing.js';
import { drawPokerTable } from './poker-table.js';
import { buildSaloonColliders } from './interior.js';

// ---------------------------------------------------------------------------
// saloonPlan — single source of truth for all saloon coordinates.
// ---------------------------------------------------------------------------
export function saloonPlan(){
  const b=TOWN.saloon;
  const x0=b.x-b.w/2, x1=b.x+b.w/2;        // west / east walls
  const z0=b.z-b.d/2, z1=b.z+b.d/2;        // north (back) / south (front)
  const gy=0;                               // ground at the saloon (flat town)
  const top=gy+b.h;                         // ceiling / roof height
  const frontZ=b.z<0 ? z1 : z0;             // front wall = south (z1)
  const backZ=b.z<0 ? z0 : z1;              // back wall = north (z0)
  const doorX=b.x;                          // door centred on facade
  const gapL=doorX-DOOR_GAP/2, gapR=doorX+DOOR_GAP/2;
  return { b, x0, x1, z0, z1, gy, top, frontZ, backZ, doorX, gapL, gapR };
}

// ---------------------------------------------------------------------------
// generateSaloon — player colliders + camera colliders.
// The building shell (walls + door + floor + shell camBoxes) is generated by
// generateTown in town-buildings.js. We add the INTERIOR furniture colliders
// and the EXTERIOR feature colliders (false front parapet, porch posts,
// chimney) here.
// ---------------------------------------------------------------------------
export function generateSaloon(ctx){
  const P=saloonPlan();
  const {b, x0, x1, z0, z1, top, frontZ, backZ} = P;
  const WT=WALL_T;

  // ---- Interior furniture colliders (player obstacles) ----
  const bc=(cx0,cz0,cx1,cz1)=>ctx.boxCol(cx0,cz0,cx1,cz1);
  const t=.12;

  // [BarCounter] — solid block collider.
  {
    const o=SALOON_LAYOUT.BarCounter;
    const [cx, , cz]=o.center, [sx, , sz]=o.size;
    bc(cx-sx/2, cz-sz/2, cx+sx/2, cz+sz/2);
  }
  // [SaloonTable01] and [SaloonTable02] — thin collider.
  for(const key of ['SaloonTable01','SaloonTable02']){
    const o=SALOON_LAYOUT[key];
    const [cx, , cz]=o.center, [sx, , sz]=o.size;
    bc(cx-sx/2+t, cz-sz/2+t, cx+sx/2-t, cz+sz/2-t);
  }
  // [Piano] — solid block against the west wall (so the player can't walk
  // through it). The piano's BACK is flush against the west wall (x=x0+WT),
  // the body extends INTO the room (east, +x) by 0.65m, and the keyboard
  // faces east. This avoids the v31 bug where the piano was placed with its
  // depth axis along X (into the wall) — half of it was inside the wall.
  if(SALOON_INCLUDE_PIANO){
    const pd=0.65, pw=1.50;
    // Piano back at x = x0 + WT (on the west wall surface).
    const pBackX=x0+WT;
    // Piano centre is pd/2 INTO the room (east of the wall).
    const pCentreX=pBackX+pd/2;
    // Piano z-centre: near the front of the room, against the west wall.
    const pCentreZ=z1-1.8;
    // Player collider: from the wall to pCentreX + pd/2, spanning the piano width.
    bc(pBackX, pCentreZ-pw/2, pCentreX+pd/2, pCentreZ+pw/2);
  }

  // ---- Camera colliders ----
  const cam=(cx0,cz0,cx1,cz1,ch,cy0=0)=>ctx.cam(cx0,cz0,cx1,cz1,ch,cy0);
  // [BarCounter] camera box.
  {
    const o=SALOON_LAYOUT.BarCounter;
    const [cx, , cz]=o.center, [sx, sy, sz]=o.size;
    cam(cx-sx/2-t, cz-sz/2-t, cx+sx/2+t, cz+sz/2+t, P.gy+sy+.05);
  }

  // ---- Exterior camera colliders ----
  // v33: reduced to only the 2 large exterior features that the camera
  // would actually clip through (the false front parapet and the porch roof
  // overhang). The 4 porch posts and the chimney are small / thin enough
  // that removing their camBoxes doesn't cause visible clipping but does
  // reduce the per-frame camera-collision work (helps FPS).
  const ffTop=P.gy+b.h+2.6+.2;
  // False front parapet (above the flat roof only).
  cam(x0-.1, z1-WALL_T/2-.05, x1+.1, z1+WALL_T/2+.05, ffTop, P.gy+b.h-.02);
  // Porch roof overhang camera box.
  const porchDepth=1.6;
  cam(x0-.4, z1-.1, x1+.4, z1+porchDepth+.3, P.gy+2.85, P.gy+2.6);

  // v54: floor prop colliders (from interior.js, simple version)
  buildSaloonColliders(ctx);
}

// ---------------------------------------------------------------------------
// drawSaloon (v51) — interiors are now baked via buildSaloonInterior (see
// interior.js). The only thing drawn per-frame here is the exterior shell
// (false front, sign, porch) via drawSaloonExterior.
// ---------------------------------------------------------------------------
export function drawSaloon(ctx){ drawSaloonExterior(ctx, saloonPlan()); }

// ---------------------------------------------------------------------------
// drawSaloonBuilding — v40: draws the FULL saloon building exterior (walls +
// flat roof + bat-wing doors) directly, NOT through bldWithDoor. This
// avoids the dark-gap bug where bldWithDoor left an empty doorway that hid
// the bat-wing doors.
//
// The bat-wing doors are drawn RIGHT IN the door gap, so they're always
// visible (no dark rectangle hiding them). The door state (open/closed) is
// read from the saloon door object in ctx.doors.
// ---------------------------------------------------------------------------
export function drawSaloonBuilding(ctx){
  const P=saloonPlan();
  const {b, x0, x1, z0, z1, gy, top, doorX, gapL, gapR, frontZ, backZ} = P;
  const WT=WALL_T;
  const wd=C.wood, dk=C.dark, pal=C.pale;

  // ---- 4 EXTERIOR WALLS ----
  // Front wall: split around the door gap BELOW, with a wall section ABOVE
  // the door (from the door top to the roof). v43: the wall above the door
  // was missing, creating a dark void above the doorway.
  const H=b.h+.03, cy=gy+H/2;
  ctx.pb((x0+gapL)/2, cy, frontZ, gapL-x0, H, WT, wd);   // front-left
  ctx.pb((gapR+x1)/2, cy, frontZ, x1-gapR, H, WT, wd);    // front-right
  // Wall section ABOVE the door (from door top to roof). This closes the
  // gap above the doorway so the wall is continuous.
  const doorTopY = gy + DOOR_H;   // top of the door opening
  const aboveH = top - doorTopY; // height of the wall section above the door
  if(aboveH > 0.02){
    const aboveCy = doorTopY + aboveH/2;
    ctx.pb(doorX, aboveCy, frontZ, DOOR_GAP, aboveH, WT, wd);
  }
  // West wall (full depth).
  ctx.pb(x0+WT/2, cy, (z0+z1)/2, WT, H, z1-z0, wd);
  // East wall (full depth).
  ctx.pb(x1-WT/2, cy, (z0+z1)/2, WT, H, z1-z0, wd);
  // Back wall (full width).
  ctx.pb((x0+x1)/2, cy, backZ, b.w, H, WT, wd);

  // ---- FLAT ROOF ----
  ctx.pb((x0+x1)/2, top+.01, (z0+z1)/2, b.w+.06, .06, b.d+.06, dk);

  // ---- BAT-WING DOORS (drawn by drawBatwingDoors from bar/batwing.js) ----
  // v46: the saloon door object is created in generateSaloonShell. Find it
  // and draw the bat-wing doors (everything rotates as a rigid body).
  const sd = ctx.doors.find(x => x.key === 'saloon');
  if (sd) drawBatwingDoors(ctx, sd, gy);

  // ---- FALSE FRONT PARAPET + SALOON SIGN + PORCH (the old drawSaloonExterior) ----
  drawSaloonExterior(ctx, P);
}

// ---------------------------------------------------------------------------
// v45: drawSaloonBatwingDoorDirect REMOVED per user request. The user will
// provide their own door code.
// ---------------------------------------------------------------------------

// Helper: get the front (south, +z) edge z of the BarCounter for placing the
// BarTowel on the customer-facing edge.
function sz_edge(o){
  return o.size[2]/2 - 0.03;
}

// ---------------------------------------------------------------------------
// drawSaloonExterior — false-front PARAPET (above the flat roof only),
// SALOON sign, porch posts, porch roof, front windows on the regular front
// wall, porch railing, and chimney.
//
// v31 fix: the false front is now a PARAPET that sits ON TOP of the front
// wall (from y=top to y=ffTop), NOT a full-height slab. This means the front
// door + windows on the regular front wall are fully visible and the door
// is no longer "stuck inside the wall".
// ---------------------------------------------------------------------------
function drawSaloonExterior(ctx, P){
  const {b, x0, x1, z0, z1, gy, top} = P;
  const WT=WALL_T;
  const wd=C.wood, dk=C.dark, w2=C.wood2, pal=C.pale, stn=C.stone, gold=C.gold;

  // ---- FALSE FRONT PARAPET ----
  // A tall flat wall sitting ON TOP of the front wall, rising above the flat
  // roof. From y=top (wall top) to y=ffTop (parapet top). Full width of the
  // building + a bit. This gives the classic tall rectangular western
  // saloon silhouette WITHOUT covering the door or windows.
  const ffTop=gy+b.h+2.6;          // parapet top
  const ffH=ffTop-top;              // parapet height (~2.6m above the roof)
  const ffW=b.w+0.6;                // slightly wider than the building
  const ffX=(x0+x1)/2;
  const ffZ=z1;                     // at the front wall
  const ffT=WALL_T+.06;             // a bit thicker than the walls
  // Parapet main slab (centred at top + ffH/2).
  ctx.pb(ffX, top+ffH/2, ffZ, ffW, ffH, ffT, pal);
  // Parapet cornice — a slightly wider trim at the very top.
  ctx.pb(ffX, ffTop+.08, ffZ, ffW+.30, .16, ffT+.20, dk);
  // Decorative band just below the cornice.
  ctx.pb(ffX, ffTop-.18, ffZ, ffW+.06, .12, ffT+.06, dk);

  // ---- "SALOON" SIGN ----
  // A large horizontal sign board mounted on the FRONT (south, +z) face of
  // the parapet. Gold border + dark inner panel + 6 gold vertical letter
  // slats suggesting "SALOON". The sign is placed at z = ffZ + ffT/2 + offset
  // so it sits PROUD of (south of) the parapet front face — visible from the
  // street, not hidden behind the parapet slab.
  const signY=top+0.9;
  const signW=b.w-1.5;
  const signH=1.00;
  const signT=0.16;
  const signZ=ffZ+ffT/2+0.20;      // 0.20m proud of the parapet front face (south)
  // Sign border frame (gold).
  ctx.pb(ffX, signY, signZ, signW+.30, signH+.30, signT, gold);
  // Sign inner panel (dark wood) — slightly south of the frame so it's
  // visible on the front face.
  ctx.pb(ffX, signY, signZ+.08, signW, signH, signT, dk);
  // ---- "BAR" letters (gold, 3D pixel-style) ----
  // Build each letter from small gold boxes on the sign's front face.
  // The sign inner panel front face is at signZ + .08 + signT/2 = signZ+.16.
  // Letters sit PROUD of that face (at signZ + .16 + .06) so they don't
  // z-fight with the panel and are clearly visible.
  const letterColor = gold;
  const letterZ = signZ + .16 + .06;  // proud of the sign panel front face
  const letterH = 0.55;        // letter height
  const letterW = 0.35;        // letter width
  const letterGap = 0.15;      // gap between letters
  const letterDepth = 0.06;    // letter thickness (proud of the panel)
  const totalW = 3*letterW + 2*letterGap;
  const letterStartX = ffX - totalW/2 + letterW/2;
  // Helper to draw a small box for a letter stroke.
  const stroke = (cx, cy, w, h) => {
    ctx.pb(cx, cy, letterZ, w, h, letterDepth, letterColor);
  };
  // Letter heights: top, middle, bottom Y positions.
  const yT = signY + letterH/2;   // top
  const yM = signY;                // middle
  const yB = signY - letterH/2;   // bottom
  const halfW = letterW/2;
  // 'B' — two vertical strokes on the left + two horizontal strokes + middle + bumps on the right
  {
    const bx = letterStartX;
    // Left vertical (full height).
    stroke(bx - halfW + 0.04, signY, 0.08, letterH);
    // Top horizontal.
    stroke(bx, yT - 0.04, letterW - 0.04, 0.08);
    // Middle horizontal.
    stroke(bx, yM, letterW - 0.08, 0.08);
    // Bottom horizontal.
    stroke(bx, yB + 0.04, letterW - 0.04, 0.08);
    // Right bumps (top + bottom halves).
    stroke(bx + halfW - 0.04, yT - letterH/4, 0.08, letterH/2 - 0.04);
    stroke(bx + halfW - 0.04, yB + letterH/4, 0.08, letterH/2 - 0.04);
  }
  // 'A' — two diagonal-ish verticals + a middle bar. Simplified as 2 verticals
  // + top join + middle bar.
  {
    const ax = letterStartX + letterW + letterGap;
    // Left vertical (slightly inward at top — simplified to vertical).
    stroke(ax - halfW + 0.06, signY, 0.08, letterH);
    // Right vertical.
    stroke(ax + halfW - 0.06, signY, 0.08, letterH);
    // Top join (a horizontal bar at the top).
    stroke(ax, yT - 0.04, letterW - 0.08, 0.08);
    // Middle bar.
    stroke(ax, yM, letterW - 0.10, 0.08);
  }
  // 'R' — left vertical + top horizontal + right bump (top half) + diagonal leg.
  {
    const rx = letterStartX + 2*(letterW + letterGap);
    // Left vertical (full height).
    stroke(rx - halfW + 0.04, signY, 0.08, letterH);
    // Top horizontal.
    stroke(rx, yT - 0.04, letterW - 0.04, 0.08);
    // Middle horizontal (shorter — only the top bowl).
    stroke(rx, yM, letterW - 0.10, 0.08);
    // Right bump (top half only).
    stroke(rx + halfW - 0.04, yT - letterH/4, 0.08, letterH/2 - 0.04);
    // Diagonal leg (a single box going down to the bottom-right).
    stroke(rx + halfW - 0.10, yB + letterH/4, 0.08, letterH/2 - 0.04);
  }
  // Hanging brackets (going back to the parapet).
  ctx.pb(ffX-signW/2+.15, signY+signH/2+.10, (ffZ+signZ)/2, .10, .20, (signZ-ffZ), dk);
  ctx.pb(ffX+signW/2-.15, signY+signH/2+.10, (ffZ+signZ)/2, .10, .20, (signZ-ffZ), dk);

  // ---- FRONT PORCH POSTS ----
  const porchDepth=1.6;
  const porchZ=z1+porchDepth/2;
  const postZ=z1+porchDepth-.10;
  const postH=gy+2.6;
  const postCy=postH/2;
  const postXs=[x0+0.4, b.x-2.4, b.x+2.4, x1-0.4];
  for(const px of postXs){
    ctx.pb(px, postCy, postZ, .22, postH, .22, dk);
    ctx.pb(px, gy+.06, postZ, .34, .12, .34, stn);
    ctx.pb(px, postH+.06, postZ, .28, .10, .28, wd);
  }

  // ---- PORCH ROOF OVERHANG ----
  const porchRoofY=gy+2.75;
  const porchRoofW=b.w+.8;
  const porchRoofD=porchDepth+.4;
  ctx.pb((x0+x1)/2, porchRoofY, porchZ, porchRoofW, .12, porchRoofD, dk);
  ctx.pb((x0+x1)/2, porchRoofY-.18, postZ, porchRoofW, .24, .06, w2);

  // ---- FRONT WINDOWS (on the regular front wall, NOT in the false front) ----
  // These sit at z1+WALL_T/2 (the outer face of the regular front wall), well
  // below the parapet (which starts at y=top). The door gap is centred at
  // b.x, so we place windows at b.x ± b.w/4 — clear of the door.
  const winYExt=gy+1.5;
  const winWext=1.6, winHext=1.8;
  for(const wx of [b.x-b.w/4, b.x+b.w/4]){
    // Window frame (raised wood border on the outer face of the front wall).
    ctx.pb(wx, winYExt, z1+WALL_T/2+.02, winWext+.16, winHext+.16, .06, pal);
    // Glass pane (dark, on the wall face).
    ctx.pb(wx, winYExt, z1+WALL_T/2, winWext, winHext, .04, [0.13,0.18,0.22]);
    // Cross bars dividing the pane into 4.
    ctx.pb(wx, winYExt, z1+WALL_T/2+.02, winWext, .06, .05, pal);
    ctx.pb(wx, winYExt, z1+WALL_T/2+.02, .06, winHext, .05, pal);
    // Shutters on the outer side of each window.
    const shX=wx> b.x ? wx+winWext/2+.18 : wx-winWext/2-.18;
    ctx.pb(shX, winYExt, z1+WALL_T/2+.10, .14, winHext, .08, dk);
    for(const sy of [winYExt-winHext/3, winYExt, winYExt+winHext/3]){
      ctx.pb(shX, sy, z1+WALL_T/2+.14, .16, .04, .04, w2);
    }
  }

  // ---- PORCH RAILING ----
  // v32: REMOVED. The railing ran across the porch edge and visually
  // appeared as a brown horizontal bar blocking the door when entering /
  // exiting. The 4 porch posts alone are enough for the western look.
  // (The rail + balusters are removed to keep the entrance fully clear.)

  // ---- CHIMNEY ----
  const chimX=x1-1.5, chimZ=z0+2.0;
  const chimBase=top, chimTop=top+2.2;
  const brick=[0.62,0.30,0.22];
  ctx.pb(chimX, (chimBase+chimTop)/2, chimZ, .54, chimTop-chimBase, .54, brick);
  ctx.pb(chimX, chimTop+.10, chimZ, .66, .20, .66, dk);
  ctx.pb(chimX, chimBase+.08, chimZ, .70, .16, .70, dk);
  for(const cy of [chimBase+.5, chimBase+1.1, chimBase+1.7]){
    ctx.pb(chimX, cy, chimZ+.28, .56, .04, .04, dk);
  }
}
