// Saloon / Bar generation and drawing — plan-driven (v31)
//
// Recreates the interior + exterior of a Western Saloon / Bar based on the
// Hyper3D Rodin reference model "Old Western saloon", using only the existing
// ctx.pb() renderer (no GLB / Three.js).
//
// v31 changes:
//   - False front is now a PARAPET above the flat roof (not a full-height
//     slab), so the front door + windows on the regular front wall are no
//     longer covered / clipped.
//   - Front windows sit on the regular front wall surface (z1+WALL_T/2),
//     not pushed into the false front.
//   - Added named interior props: Spittoon, WantedPoster01/02, SaloonPainting,
//     AntlerMount, CardDeck, PokerChips, PokerTableCloth, WhiskeyBottle,
//     BeerBarrel, BarTowel, WallSconce01/02.
//   - Added an upright Piano (from piano.js) against the west wall, with a
//     PianoStool.
//   - Code moved into src/game/bar/ folder.
//
// All coords are derived from the TOWN.saloon bounding box. A clear visitor
// path runs along x = b.x = -28.5 from the front door (z = z1) straight north
// to the bar counter (z ≈ -9.7). Tables sit either side of this path; stools
// sit in front of the counter; shelves sit on the back wall behind the bar.

import {
  TOWN, DOOR_GAP, DOOR_H, WALL_T, DOOR_SPEED, C,
  SALOON_LAYOUT, SALOON_INCLUDE_PIANO
} from '../config.js';
import { V3 } from '../math.js';
import { drawPiano, drawPianoStool } from './piano.js';

// ---------------------------------------------------------------------------
// saloonPlan — single source of truth for all saloon coordinates.
// ---------------------------------------------------------------------------
export function saloonPlan(){
  const b=TOWN.saloon;
  const x0=b.x-b.w/2, x1=b.x+b.w/2;        // west / east walls
  const z0=b.z-b.d/2, z1=b.z+b.d/2;        // north (back) / south (front)
  const gy=0;                               // ground at the saloon (flat town)
  const top=gy+b.h;                         // ceiling / roof height
  const frontZ=b.z<0 ? z1 : z0;             // front wall = south (z1)
  const backZ=b.z<0 ? z0 : z1;              // back wall = north (z0)
  const doorX=b.x;                          // door centred on facade
  const gapL=doorX-DOOR_GAP/2, gapR=doorX+DOOR_GAP/2;
  return { b, x0, x1, z0, z1, gy, top, frontZ, backZ, doorX, gapL, gapR };
}

// ---------------------------------------------------------------------------
// generateSaloon — player colliders + camera colliders.
// The building shell (walls + door + floor + shell camBoxes) is generated by
// generateTown in town-buildings.js. We add the INTERIOR furniture colliders
// and the EXTERIOR feature colliders (false front parapet, porch posts,
// chimney) here.
// ---------------------------------------------------------------------------
export function generateSaloon(ctx){
  const P=saloonPlan();
  const {b, x0, x1, z0, z1, top, frontZ, backZ} = P;
  const WT=WALL_T;

  // ---- Interior furniture colliders (player obstacles) ----
  const bc=(cx0,cz0,cx1,cz1)=>ctx.boxCol(cx0,cz0,cx1,cz1);
  const t=.12;

  // [BarCounter] — solid block collider.
  {
    const o=SALOON_LAYOUT.BarCounter;
    const [cx, , cz]=o.center, [sx, , sz]=o.size;
    bc(cx-sx/2, cz-sz/2, cx+sx/2, cz+sz/2);
  }
  // [SaloonTable01] and [SaloonTable02] — thin collider.
  for(const key of ['SaloonTable01','SaloonTable02']){
    const o=SALOON_LAYOUT[key];
    const [cx, , cz]=o.center, [sx, , sz]=o.size;
    bc(cx-sx/2+t, cz-sz/2+t, cx+sx/2-t, cz+sz/2-t);
  }
  // [Piano] — solid block against the west wall (so the player can't walk
  // through it). The piano's BACK is flush against the west wall (x=x0+WT),
  // the body extends INTO the room (east, +x) by 0.65m, and the keyboard
  // faces east. This avoids the v31 bug where the piano was placed with its
  // depth axis along X (into the wall) — half of it was inside the wall.
  if(SALOON_INCLUDE_PIANO){
    const pd=0.65, pw=1.50;
    // Piano back at x = x0 + WT (on the west wall surface).
    const pBackX=x0+WT;
    // Piano centre is pd/2 INTO the room (east of the wall).
    const pCentreX=pBackX+pd/2;
    // Piano z-centre: near the front of the room, against the west wall.
    const pCentreZ=z1-1.8;
    // Player collider: from the wall to pCentreX + pd/2, spanning the piano width.
    bc(pBackX, pCentreZ-pw/2, pCentreX+pd/2, pCentreZ+pw/2);
  }

  // ---- Camera colliders ----
  const cam=(cx0,cz0,cx1,cz1,ch,cy0=0)=>ctx.cam(cx0,cz0,cx1,cz1,ch,cy0);
  // [BarCounter] camera box.
  {
    const o=SALOON_LAYOUT.BarCounter;
    const [cx, , cz]=o.center, [sx, sy, sz]=o.size;
    cam(cx-sx/2-t, cz-sz/2-t, cx+sx/2+t, cz+sz/2+t, P.gy+sy+.05);
  }

  // ---- Exterior camera colliders ----
  // v33: reduced to only the 2 large exterior features that the camera
  // would actually clip through (the false front parapet and the porch roof
  // overhang). The 4 porch posts and the chimney are small / thin enough
  // that removing their camBoxes doesn't cause visible clipping but does
  // reduce the per-frame camera-collision work (helps FPS).
  const ffTop=P.gy+b.h+2.6+.2;
  // False front parapet (above the flat roof only).
  cam(x0-.1, z1-WALL_T/2-.05, x1+.1, z1+WALL_T/2+.05, ffTop, P.gy+b.h-.02);
  // Porch roof overhang camera box.
  const porchDepth=1.6;
  cam(x0-.4, z1-.1, x1+.4, z1+porchDepth+.3, P.gy+2.85, P.gy+2.6);
}

// ---------------------------------------------------------------------------
// drawSaloon — renders the interior + exterior of the saloon. The exterior
// shell (walls + flat roof + door) is drawn by bldWithDoor in town-buildings.js;
// we draw the interior furniture, the exterior false-front parapet + sign +
// porch, and the piano.
// ---------------------------------------------------------------------------
export function drawSaloon(ctx){
  const P=saloonPlan();
  const {b, x0, x1, z0, z1, gy, top} = P;
  const WT=WALL_T;
  const wd=C.wood, dk=C.dark, w2=C.wood2, pal=C.pale, stn=C.stone;
  const gold=C.gold;

  // ========== BAR COUNTER ==========
  {
    const o=SALOON_LAYOUT.BarCounter;
    const [cx, cy, cz]=o.center, [sx, sy, sz]=o.size;
    // Counter top (overhanging the customer side).
    ctx.pb(cx, gy+sy-.05, cz, sx, .10, sz+.10, w2);
    // Counter body.
    ctx.pb(cx, cy, cz, sx, sy-.10, sz, wd);
    // Front fascia panel (customer-facing, south).
    ctx.pb(cx, cy, cz+sz/2-.03, sx-.10, sy-.20, .04, dk);
    // Bartender rail behind the counter top.
    ctx.pb(cx, gy+sy+.02, cz-sz/2+.05, sx, .06, .10, dk);
    // 3 drawer-fronts on the customer side.
    for(let i=-1; i<=1; i++){
      ctx.pb(cx+i*3.0, gy+.35, cz+sz/2+.01, .80, .25, .03, dk);
      ctx.pb(cx+i*3.0, gy+.45, cz+sz/2+.03, .20, .02, .03, pal);
    }
  }

  // ========== BAR STOOLS ==========
  for(const key of ['BarStool01','BarStool02','BarStool03','BarStool04']){
    const o=SALOON_LAYOUT[key];
    if(!o) continue;
    const [cx, cy, cz]=o.center;
    ctx.pb(cx, gy+.45, cz, .40, .06, .40, wd);
    ctx.pb(cx, gy+.47, cz, .44, .04, .44, dk);
    ctx.pb(cx, gy+.22, cz, .06, .44, .06, dk);
    ctx.pb(cx-.15, gy+.05, cz-.10, .05, .10, .05, dk);
    ctx.pb(cx+.15, gy+.05, cz-.10, .05, .10, .05, dk);
    ctx.pb(cx, gy+.05, cz+.15, .05, .10, .05, dk);
  }

  // ========== SALOON TABLES ==========
  for(const tKey of ['SaloonTable01','SaloonTable02']){
    const o=SALOON_LAYOUT[tKey];
    if(!o) continue;
    const [cx, , cz]=o.center, [sx, , sz]=o.size;
    // Table top.
    ctx.pb(cx, gy+.78, cz, sx, .06, sz, wd);
    // Table top edge.
    ctx.pb(cx, gy+.80, cz, sx+.06, .03, sz+.06, dk);
    // Centre pedestal.
    ctx.pb(cx, gy+.39, cz, .10, .78, .10, dk);
    // Pedestal base.
    ctx.pb(cx, gy+.03, cz, .40, .06, .40, dk);
  }

  // ========== POKER TABLE CLOTH (SaloonTable01 becomes a poker table) ==========
  // [PokerTableCloth] — a green felt cloth on SaloonTable01 marking it as the
  // card / poker table.
  {
    const o=SALOON_LAYOUT.SaloonTable01;
    const [cx, , cz]=o.center, [sx, , sz]=o.size;
    ctx.pb(cx, gy+.82, cz, sx-.02, .02, sz-.02, [0.18, 0.42, 0.22]);
    // A thin darker border on the felt.
    ctx.pb(cx, gy+.83, cz, sx-.02, .01, .04, [0.10, 0.28, 0.14]);
    ctx.pb(cx, gy+.83, cz, .04, .01, sz-.02, [0.10, 0.28, 0.14]);
  }

  // ========== SALOON CHAIRS ==========
  for(const key of ['SaloonChair01','SaloonChair02','SaloonChair03','SaloonChair04',
                    'SaloonChair05','SaloonChair06','SaloonChair07','SaloonChair08']){
    const o=SALOON_LAYOUT[key];
    if(!o) continue;
    const [cx, , cz]=o.center;
    let tableCentre=null;
    if(key<='SaloonChair04') tableCentre=SALOON_LAYOUT.SaloonTable01.center;
    else tableCentre=SALOON_LAYOUT.SaloonTable02.center;
    const [tcx, , tcz]=tableCentre;
    const dx=cx-tcx, dz=cz-tcz;
    ctx.pb(cx, gy+.45, cz, .44, .06, .44, wd);
    ctx.pb(cx-.18, gy+.22, cz-.18, .05, .44, .05, dk);
    ctx.pb(cx+.18, gy+.22, cz-.18, .05, .44, .05, dk);
    ctx.pb(cx-.18, gy+.22, cz+.18, .05, .44, .05, dk);
    ctx.pb(cx+.18, gy+.22, cz+.18, .05, .44, .05, dk);
    const off=.20;
    if(Math.abs(dx)>Math.abs(dz)){
      const sign=dx>0?1:-1;
      ctx.pb(cx+sign*off, gy+.68, cz, .06, .42, .44, wd);
    }else{
      const sign=dz>0?1:-1;
      ctx.pb(cx, gy+.68, cz+sign*off, .44, .42, .06, wd);
    }
  }

  // ========== BAR SHELVES + BOTTLES ==========
  for(const key of ['BarShelfLower','BarShelfUpper']){
    const o=SALOON_LAYOUT[key];
    if(!o) continue;
    const [cx, cy, cz]=o.center, [sx, , sz]=o.size;
    ctx.pb(cx, cy, cz, sx, .06, sz, w2);
    ctx.pb(cx-sx/2+.15, cy-.10, cz, .04, .20, .10, dk);
    ctx.pb(cx+sx/2-.15, cy-.10, cz, .04, .20, .10, dk);
    const bottleColors=[
      [0.45,0.62,0.40],[0.55,0.30,0.20],[0.30,0.40,0.60],[0.65,0.55,0.30],
      [0.40,0.20,0.20],[0.55,0.30,0.20],[0.45,0.62,0.40],[0.30,0.40,0.60],
      [0.65,0.55,0.30],[0.40,0.20,0.20],[0.55,0.30,0.20],[0.45,0.62,0.40],
    ];
    const count=12, spacing=sx/(count+1);
    for(let i=0; i<count; i++){
      const bx=cx-sx/2+spacing*(i+1);
      const by=cy+.12;
      const c=bottleColors[i%bottleColors.length];
      ctx.pb(bx, by, cz, .10, .24, .10, c);
      ctx.pb(bx, by+.16, cz, .04, .08, .04, c);
    }
  }

  // ========== HANGING LAMPS ==========
  for(const key of ['SaloonLamp01','SaloonLamp02']){
    const o=SALOON_LAYOUT[key];
    if(!o) continue;
    const [cx, cy, cz]=o.center, [sx, sy, sz]=o.size;
    ctx.pb(cx, top-.10, cz, .03, .30, .03, dk);
    ctx.pb(cx, top-.40, cz, .14, .08, .14, dk);
    ctx.pb(cx, cy+.05, cz, sx, sy*.4, sz, dk);
    ctx.pb(cx, cy-.10, cz, sx+.06, .06, sz+.06, dk);
    ctx.pb(cx, cy-.15, cz, sx-.06, .04, sz-.06, [1.0,0.85,0.5]);
  }

  // ========== PIANO (upright, against the west wall) ==========
  // [Piano] — upright walnut piano, BACK flush against the west wall
  // (x = x0 + WT), body extends INTO the room (east, +x), keyboard faces
  // east. This is the v32 fix: the piano is rotated 90° so its back is
  // against the wall, not half-buried in it.
  if(SALOON_INCLUDE_PIANO){
    const pd=0.65, pw=1.50;
    const pBackX=x0+WT;               // piano back on the west wall
    const pCentreX=pBackX+pd/2;       // piano centre (pd/2 into the room)
    const pCentreZ=z1-1.8;            // near the front of the room
    drawPiano(ctx, pBackX, pCentreZ, gy, 'E');   // keyboard faces east (+x)
    // [PianoStool] — small round stool in front of the keyboard (east of
    // the piano, further into the room).
    drawPianoStool(ctx, pCentreX + 0.85, pCentreZ, gy);
  }

  // ========== NAMED INTERIOR PROPS (small visual objects) ==========
  // Each prop has a stable name so it can be referenced and edited later.

  // [Spittoon] — a brass spittoon at the foot of the bar (customer side,
  // near the west end of the counter).
  {
    const spX=x0+1.2, spZ=z1-3.0;
    ctx.pb(spX, gy+.10, spZ, .22, .04, .22, gold);       // rim
    ctx.pb(spX, gy+.06, spZ, .20, .08, .20, [0.60,0.48,0.18]); // body (brass)
    ctx.pb(spX, gy+.12, spZ, .24, .02, .24, gold);        // lip
  }

  // [WantedPoster01] — a "WANTED" poster on the WEST wall, near the front.
  // Mounted IN THE ROOM (x = x0 + WT + 0.04). Placed at z=z1-2.2 (front of
  // the room), CLEAR of the west-wall window which spans z=-8.3..-6.7.
  {
    const wpX=x0+WT+0.04, wpY=gy+1.7, wpZ=z1-2.2;       // z=-5.7, clear of window
    ctx.pb(wpX, wpY, wpZ, .04, .50, .38, pal);           // paper
    ctx.pb(wpX, wpY+.18, wpZ, .05, .10, .36, [0.78,0.20,0.18]); // red "WANTED" band
    for(const ly of [-0.04, -0.08, -0.12, -0.16]){
      ctx.pb(wpX, wpY+ly, wpZ, .28, .01, .01, dk);
    }
    ctx.pb(wpX, wpY-.04, wpZ, .08, .10, .08, dk);
  }

  // [WantedPoster02] — another "WANTED" poster on the EAST wall, near the
  // BACK of the room (z=z0+2.5). Placed CLEAR of the east-wall window which
  // spans z=-8.3..-6.7.
  {
    const wpX=x1-WT-0.04, wpY=gy+1.6, wpZ=z0+2.5;       // z=-9.0, clear of window
    ctx.pb(wpX, wpY, wpZ, .04, .44, .34, pal);
    ctx.pb(wpX, wpY+.15, wpZ, .05, .08, .32, [0.78,0.20,0.18]);
    for(const ly of [-0.04, -0.08, -0.12]){
      ctx.pb(wpX, wpY+ly, wpZ, .24, .01, .01, dk);
    }
    ctx.pb(wpX, wpY-.06, wpZ, .06, .08, .06, dk);
  }

  // [SaloonPainting] — a framed painting on the EAST wall, near the FRONT
  // of the room (z=z1-1.5). Placed CLEAR of the east-wall window (z=-8.3..-6.7)
  // and clear of WantedPoster02 (z=-9.0).
  {
    const paX=x1-WT-0.05, paY=gy+2.0, paZ=z1-1.5;      // z=-5.0, clear
    ctx.pb(paX, paY, paZ, .06, .80, 1.00, pal);          // frame
    ctx.pb(paX, paY, paZ, .04, .72, .92, dk);            // canvas
    ctx.pb(paX-.02, paY, paZ, .04, .10, .92, [0.55,0.40,0.25]); // horizon
    ctx.pb(paX-.02, paY+.30, paZ, .04, .30, .92, [0.45,0.50,0.62]); // sky
    ctx.pb(paX-.02, paY+.42, paZ+.30, .04, .10, .10, [0.95,0.80,0.40]); // sun
  }

  // [AntlerMount] — a deer-antler mount on the BACK (north) wall, above the
  // upper shelf. Mounted IN THE ROOM (z = z0 + WT + 0.04 — just inside the
  // north wall).
  {
    const amX=b.x+3.0, amY=gy+2.6, amZ=z0+WT+0.04;
    ctx.pb(amX, amY, amZ, .30, .40, .04, wd);            // plaque
    for(const side of [-1, 1]){
      for(let i=0; i<3; i++){
        const ay=amY + 0.10 - i*0.10;
        const ax=amX + side*(0.18 + i*0.06);
        ctx.pb(ax, ay, amZ, .18, .03, .03, [0.85,0.78,0.65]);
        ctx.pb(ax + side*0.06, ay+.08, amZ, .03, .10, .03, [0.85,0.78,0.65]);
      }
    }
  }

  // [CardDeck] — a deck of playing cards on the poker table (SaloonTable01).
  {
    const o=SALOON_LAYOUT.SaloonTable01;
    const [cx, , cz]=o.center;
    // The deck (a small stack of white cards with a red top).
    ctx.pb(cx-.20, gy+.84, cz+.10, .18, .04, .14, [0.95,0.93,0.86]);
    ctx.pb(cx-.20, gy+.87, cz+.10, .18, .01, .14, [0.78,0.20,0.20]);
    // A couple of cards laid out next to the deck.
    ctx.pb(cx+.20, gy+.83, cz-.05, .12, .01, .08, [0.95,0.93,0.86]);
    ctx.pb(cx+.20, gy+.84, cz-.05, .04, .01, .04, [0.78,0.20,0.20]);
  }

  // [PokerChips] — stacks of poker chips on the poker table.
  {
    const o=SALOON_LAYOUT.SaloonTable01;
    const [cx, , cz]=o.center;
    // Red chip stack (3 chips).
    for(let i=0; i<3; i++){
      ctx.pb(cx+.15, gy+.83+i*0.02, cz+.20, .14, .02, .14, [0.78,0.18,0.18]);
    }
    // White chip stack (2 chips).
    for(let i=0; i<2; i++){
      ctx.pb(cx-.15, gy+.83+i*0.02, cz-.20, .14, .02, .14, [0.92,0.90,0.82]);
    }
    // Blue chip (single).
    ctx.pb(cx-.05, gy+.83, cz+.05, .14, .02, .14, [0.25,0.40,0.62]);
  }

  // [WhiskeyBottle] — a whiskey bottle on SaloonTable02 (the non-poker table),
  // tipped on its side in a small glass.
  {
    const o=SALOON_LAYOUT.SaloonTable02;
    const [cx, , cz]=o.center;
    // Bottle standing upright.
    ctx.pb(cx-.25, gy+.85, cz, .10, .24, .10, [0.45,0.30,0.18]);
    ctx.pb(cx-.25, gy+.99, cz, .04, .08, .04, [0.45,0.30,0.18]);
    // A glass next to it.
    ctx.pb(cx+.20, gy+.83, cz, .07, .08, .07, [0.85,0.85,0.7]);
    // Amber liquid in the glass.
    ctx.pb(cx+.20, gy+.85, cz, .06, .05, .06, [0.78,0.55,0.20]);
  }

  // [BeerBarrel] — a small wooden beer barrel on the floor behind the bar
  // counter (in the bartender walkway, near the west end).
  {
    const bbX=x0+1.5, bbZ=z0+1.5;
    // Barrel body (2 staves slabs + 2 hoop bands).
    ctx.pb(bbX, gy+.45, bbZ, .55, .90, .55, w2);
    // Top + bottom caps.
    ctx.pb(bbX, gy+.90, bbZ, .55, .04, .55, wd);
    ctx.pb(bbX, gy+.02, bbZ, .55, .04, .55, wd);
    // 2 dark hoop bands.
    ctx.pb(bbX, gy+.70, bbZ, .57, .06, .57, dk);
    ctx.pb(bbX, gy+.20, bbZ, .57, .06, .57, dk);
    // A spigot (brass tap) on the front.
    ctx.pb(bbX+.28, gy+.50, bbZ, .10, .04, .04, gold);
    ctx.pb(bbX+.34, gy+.50, bbZ, .04, .04, .10, gold);
  }

  // [BarTowel] — a towel hanging on the front edge of the bar counter.
  {
    const o=SALOON_LAYOUT.BarCounter;
    const [cx, , cz]=o.center;
    // Towel on the counter top (a small folded cloth).
    ctx.pb(cx+2.5, gy+1.16, cz+sz_edge(o), .30, .02, .20, [0.80,0.75,0.65]);
    // Hanging down a bit.
    ctx.pb(cx+2.5, gy+1.05, cz+sz_edge(o), .30, .12, .04, [0.80,0.75,0.65]);
  }

  // [WallSconce01] — a wall-mounted oil lamp on the WEST wall, near the BACK
  // of the room. Placed at z=z0+2.5 (=-9.0), CLEAR of the west-wall window
  // (z=-8.3..-6.7). Mounted IN THE ROOM (x = x0 + WT + 0.08).
  {
    const wsX=x0+WT+0.08, wsY=gy+2.0, wsZ=z0+2.5;        // z=-9.0, clear of window
    ctx.pb(wsX, wsY, wsZ, .04, .20, .20, dk);            // backing plate
    ctx.pb(wsX+.06, wsY, wsZ, .10, .18, .10, dk);        // lamp body
    ctx.pb(wsX+.10, wsY+.05, wsZ, .06, .16, .06, [0.85,0.85,0.7]); // chimney
    ctx.pb(wsX+.10, wsY+.15, wsZ, .03, .05, .03, [1.0,0.75,0.3]);  // flame
  }

  // [WallSconce02] — a matching wall lamp on the EAST wall, near the FRONT.
  // Placed at z=z1-2.0 (=-5.5), CLEAR of the east-wall window. Mounted IN THE ROOM.
  {
    const wsX=x1-WT-0.08, wsY=gy+2.0, wsZ=z1-2.0;        // z=-5.5, clear of window
    ctx.pb(wsX, wsY, wsZ, .04, .20, .20, dk);
    ctx.pb(wsX-.06, wsY, wsZ, .10, .18, .10, dk);
    ctx.pb(wsX-.10, wsY+.05, wsZ, .06, .16, .06, [0.85,0.85,0.7]);
    ctx.pb(wsX-.10, wsY+.15, wsZ, .03, .05, .03, [1.0,0.75,0.3]);
  }

  // ========== INTERIOR WALL DETAIL: wainscoting ==========
  // A thin dark wooden band running around the lower part of all interior
  // walls. Placed just INSIDE the wall surfaces (at x0+WT, x1-WT, z0+WT,
  // z1-WT — the interior face of each wall) so it doesn't clip into the
  // walls.
  const wainscotY=gy+.60, wainscotH=.04, wainscotD=.04;
  ctx.pb((x0+x1)/2, wainscotY, z0+WT+0.02, x1-x0-2*WT, wainscotH, wainscotD, dk);  // north
  ctx.pb((x0+x1)/2, wainscotY, z1-WT-0.02, x1-x0-2*WT, wainscotH, wainscotD, dk);  // south
  ctx.pb(x0+WT+0.02, wainscotY, (z0+z1)/2, wainscotD, wainscotH, z1-z0-2*WT, dk);  // west
  ctx.pb(x1-WT-0.02, wainscotY, (z0+z1)/2, wainscotD, wainscotH, z1-z0-2*WT, dk);  // east

  // ========== CEILING BEAMS ==========
  for(let bz=z0+1.5; bz<=z1-1.5; bz+=2.0){
    ctx.pb((x0+x1)/2, top-.12, bz, x1-x0-2*WT-.2, .16, .20, dk);
  }

  // ========== INTERIOR WINDOW SILLS ==========
  // On the interior face of the front wall (z = z1 - WT) and side walls.
  const winY=gy+1.4;
  for(const wx of [b.x-b.w/4, b.x+b.w/4]){
    ctx.pb(wx, winY-.10, z1-WT-0.02, 1.6, .06, .12, wd);     // sill (just inside)
    ctx.pb(wx, winY+.40, z1-WT-0.01, 1.4, .80, .04, [0.13,0.18,0.22]); // pane
  }
  for(const sx of [x0+WT+0.02, x1-WT-0.02]){
    ctx.pb(sx, winY-.10, (z0+z1)/2, .12, .06, 1.6, wd);      // sill (just inside)
    ctx.pb(sx, winY+.40, (z0+z1)/2, .04, .80, 1.4, [0.13,0.18,0.22]); // pane
  }

  // ========== EXTERIOR: FALSE FRONT PARAPET + SALOON SIGN + PORCH ==========
  drawSaloonExterior(ctx, P);
}

// Helper: get the front (south, +z) edge z of the BarCounter for placing the
// BarTowel on the customer-facing edge.
function sz_edge(o){
  return o.size[2]/2 - 0.03;
}

// ---------------------------------------------------------------------------
// drawSaloonExterior — false-front PARAPET (above the flat roof only),
// SALOON sign, porch posts, porch roof, front windows on the regular front
// wall, porch railing, and chimney.
//
// v31 fix: the false front is now a PARAPET that sits ON TOP of the front
// wall (from y=top to y=ffTop), NOT a full-height slab. This means the front
// door + windows on the regular front wall are fully visible and the door
// is no longer "stuck inside the wall".
// ---------------------------------------------------------------------------
function drawSaloonExterior(ctx, P){
  const {b, x0, x1, z0, z1, gy, top} = P;
  const WT=WALL_T;
  const wd=C.wood, dk=C.dark, w2=C.wood2, pal=C.pale, stn=C.stone, gold=C.gold;

  // ---- FALSE FRONT PARAPET ----
  // A tall flat wall sitting ON TOP of the front wall, rising above the flat
  // roof. From y=top (wall top) to y=ffTop (parapet top). Full width of the
  // building + a bit. This gives the classic tall rectangular western
  // saloon silhouette WITHOUT covering the door or windows.
  const ffTop=gy+b.h+2.6;          // parapet top
  const ffH=ffTop-top;              // parapet height (~2.6m above the roof)
  const ffW=b.w+0.6;                // slightly wider than the building
  const ffX=(x0+x1)/2;
  const ffZ=z1;                     // at the front wall
  const ffT=WALL_T+.06;             // a bit thicker than the walls
  // Parapet main slab (centred at top + ffH/2).
  ctx.pb(ffX, top+ffH/2, ffZ, ffW, ffH, ffT, pal);
  // Parapet cornice — a slightly wider trim at the very top.
  ctx.pb(ffX, ffTop+.08, ffZ, ffW+.30, .16, ffT+.20, dk);
  // Decorative band just below the cornice.
  ctx.pb(ffX, ffTop-.18, ffZ, ffW+.06, .12, ffT+.06, dk);

  // ---- "SALOON" SIGN ----
  // A large horizontal sign board mounted on the FRONT (south, +z) face of
  // the parapet. Gold border + dark inner panel + 6 gold vertical letter
  // slats suggesting "SALOON". The sign is placed at z = ffZ + ffT/2 + offset
  // so it sits PROUD of (south of) the parapet front face — visible from the
  // street, not hidden behind the parapet slab.
  const signY=top+0.9;
  const signW=b.w-1.5;
  const signH=1.00;
  const signT=0.16;
  const signZ=ffZ+ffT/2+0.20;      // 0.20m proud of the parapet front face (south)
  // Sign border frame (gold).
  ctx.pb(ffX, signY, signZ, signW+.30, signH+.30, signT, gold);
  // Sign inner panel (dark wood) — slightly south of the frame so it's
  // visible on the front face.
  ctx.pb(ffX, signY, signZ+.08, signW, signH, signT, dk);
  // ---- "BAR" letters (gold, 3D pixel-style) ----
  // Build each letter from small gold boxes on the sign's front face.
  // The sign inner panel front face is at signZ + .08 + signT/2 = signZ+.16.
  // Letters sit PROUD of that face (at signZ + .16 + .06) so they don't
  // z-fight with the panel and are clearly visible.
  const letterColor = gold;
  const letterZ = signZ + .16 + .06;  // proud of the sign panel front face
  const letterH = 0.55;        // letter height
  const letterW = 0.35;        // letter width
  const letterGap = 0.15;      // gap between letters
  const letterDepth = 0.06;    // letter thickness (proud of the panel)
  const totalW = 3*letterW + 2*letterGap;
  const letterStartX = ffX - totalW/2 + letterW/2;
  // Helper to draw a small box for a letter stroke.
  const stroke = (cx, cy, w, h) => {
    ctx.pb(cx, cy, letterZ, w, h, letterDepth, letterColor);
  };
  // Letter heights: top, middle, bottom Y positions.
  const yT = signY + letterH/2;   // top
  const yM = signY;                // middle
  const yB = signY - letterH/2;   // bottom
  const halfW = letterW/2;
  // 'B' — two vertical strokes on the left + two horizontal strokes + middle + bumps on the right
  {
    const bx = letterStartX;
    // Left vertical (full height).
    stroke(bx - halfW + 0.04, signY, 0.08, letterH);
    // Top horizontal.
    stroke(bx, yT - 0.04, letterW - 0.04, 0.08);
    // Middle horizontal.
    stroke(bx, yM, letterW - 0.08, 0.08);
    // Bottom horizontal.
    stroke(bx, yB + 0.04, letterW - 0.04, 0.08);
    // Right bumps (top + bottom halves).
    stroke(bx + halfW - 0.04, yT - letterH/4, 0.08, letterH/2 - 0.04);
    stroke(bx + halfW - 0.04, yB + letterH/4, 0.08, letterH/2 - 0.04);
  }
  // 'A' — two diagonal-ish verticals + a middle bar. Simplified as 2 verticals
  // + top join + middle bar.
  {
    const ax = letterStartX + letterW + letterGap;
    // Left vertical (slightly inward at top — simplified to vertical).
    stroke(ax - halfW + 0.06, signY, 0.08, letterH);
    // Right vertical.
    stroke(ax + halfW - 0.06, signY, 0.08, letterH);
    // Top join (a horizontal bar at the top).
    stroke(ax, yT - 0.04, letterW - 0.08, 0.08);
    // Middle bar.
    stroke(ax, yM, letterW - 0.10, 0.08);
  }
  // 'R' — left vertical + top horizontal + right bump (top half) + diagonal leg.
  {
    const rx = letterStartX + 2*(letterW + letterGap);
    // Left vertical (full height).
    stroke(rx - halfW + 0.04, signY, 0.08, letterH);
    // Top horizontal.
    stroke(rx, yT - 0.04, letterW - 0.04, 0.08);
    // Middle horizontal (shorter — only the top bowl).
    stroke(rx, yM, letterW - 0.10, 0.08);
    // Right bump (top half only).
    stroke(rx + halfW - 0.04, yT - letterH/4, 0.08, letterH/2 - 0.04);
    // Diagonal leg (a single box going down to the bottom-right).
    stroke(rx + halfW - 0.10, yB + letterH/4, 0.08, letterH/2 - 0.04);
  }
  // Hanging brackets (going back to the parapet).
  ctx.pb(ffX-signW/2+.15, signY+signH/2+.10, (ffZ+signZ)/2, .10, .20, (signZ-ffZ), dk);
  ctx.pb(ffX+signW/2-.15, signY+signH/2+.10, (ffZ+signZ)/2, .10, .20, (signZ-ffZ), dk);

  // ---- FRONT PORCH POSTS ----
  const porchDepth=1.6;
  const porchZ=z1+porchDepth/2;
  const postZ=z1+porchDepth-.10;
  const postH=gy+2.6;
  const postCy=postH/2;
  const postXs=[x0+0.4, b.x-2.4, b.x+2.4, x1-0.4];
  for(const px of postXs){
    ctx.pb(px, postCy, postZ, .22, postH, .22, dk);
    ctx.pb(px, gy+.06, postZ, .34, .12, .34, stn);
    ctx.pb(px, postH+.06, postZ, .28, .10, .28, wd);
  }

  // ---- PORCH ROOF OVERHANG ----
  const porchRoofY=gy+2.75;
  const porchRoofW=b.w+.8;
  const porchRoofD=porchDepth+.4;
  ctx.pb((x0+x1)/2, porchRoofY, porchZ, porchRoofW, .12, porchRoofD, dk);
  ctx.pb((x0+x1)/2, porchRoofY-.18, postZ, porchRoofW, .24, .06, w2);

  // ---- FRONT WINDOWS (on the regular front wall, NOT in the false front) ----
  // These sit at z1+WALL_T/2 (the outer face of the regular front wall), well
  // below the parapet (which starts at y=top). The door gap is centred at
  // b.x, so we place windows at b.x ± b.w/4 — clear of the door.
  const winYExt=gy+1.5;
  const winWext=1.6, winHext=1.8;
  for(const wx of [b.x-b.w/4, b.x+b.w/4]){
    // Window frame (raised wood border on the outer face of the front wall).
    ctx.pb(wx, winYExt, z1+WALL_T/2+.02, winWext+.16, winHext+.16, .06, pal);
    // Glass pane (dark, on the wall face).
    ctx.pb(wx, winYExt, z1+WALL_T/2, winWext, winHext, .04, [0.13,0.18,0.22]);
    // Cross bars dividing the pane into 4.
    ctx.pb(wx, winYExt, z1+WALL_T/2+.02, winWext, .06, .05, pal);
    ctx.pb(wx, winYExt, z1+WALL_T/2+.02, .06, winHext, .05, pal);
    // Shutters on the outer side of each window.
    const shX=wx> b.x ? wx+winWext/2+.18 : wx-winWext/2-.18;
    ctx.pb(shX, winYExt, z1+WALL_T/2+.10, .14, winHext, .08, dk);
    for(const sy of [winYExt-winHext/3, winYExt, winYExt+winHext/3]){
      ctx.pb(shX, sy, z1+WALL_T/2+.14, .16, .04, .04, w2);
    }
  }

  // ---- PORCH RAILING ----
  // v32: REMOVED. The railing ran across the porch edge and visually
  // appeared as a brown horizontal bar blocking the door when entering /
  // exiting. The 4 porch posts alone are enough for the western look.
  // (The rail + balusters are removed to keep the entrance fully clear.)

  // ---- CHIMNEY ----
  const chimX=x1-1.5, chimZ=z0+2.0;
  const chimBase=top, chimTop=top+2.2;
  const brick=[0.62,0.30,0.22];
  ctx.pb(chimX, (chimBase+chimTop)/2, chimZ, .54, chimTop-chimBase, .54, brick);
  ctx.pb(chimX, chimTop+.10, chimZ, .66, .20, .66, dk);
  ctx.pb(chimX, chimBase+.08, chimZ, .70, .16, .70, dk);
  for(const cy of [chimBase+.5, chimBase+1.1, chimBase+1.7]){
    ctx.pb(chimX, cy, chimZ+.28, .56, .04, .04, dk);
  }
}
